### ISSUE TITLE
How should I login my premium account?

### ISSUE THREAD

**Issue by Troublor** [emacs-grammarly/unofficial-grammarly-language-server#2]
I am using this Grammarly language server in neovim. 
The LSP works out of the box as an anonymous user to Grammarly. 
But I have a premium account and I want to use those premium features. 
How should I login to my account using the Grammarly language server?

**Comment by jcs090218** [comment]
The login logic has to be stored in the client side. You might need to ask whoever implements the client to handle this feature.

* VSCode: https://github.com/emacs-grammarly/unofficial-grammarly-language-server/blob/main/extension/src/services/AuthenticationService.ts
* Emacs (lsp-mode): https://github.com/emacs-grammarly/lsp-grammarly/blob/master/lsp-grammarly.el#L330-L456

**Extra information:**

See the document [Using a Paid Grammarly Account](https://github.com/emacs-grammarly/lsp-grammarly#money_with_wings-using-a-paid-grammarly-account). It's easier to login with VSCode. Or for the harder route (if you don't want to use VSCode), you would need to enter authentication information directly using [keytar-cli](https://github.com/emacs-grammarly/keytar-cli).

Hope these help! :)

**Comment by Troublor** [comment]
Thanks. I am using NeoVIm, and it seems [nvim-lspconfig](https://github.com/neovim/nvim-lspconfig) does not provide similar guidelines to those in Emacs. Maybe I can ask them there or do some hacking in Lua following the implementation of Emacs or VSCode.
